services:
  app:
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./static:/app/static
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8002/health/ || wget -q --spider http://localhost:8002/health/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - expenselit-network
    environment:
      - LOG_FORMAT=json

  db:
    image: postgres:16.9-alpine
    environment:
      POSTGRES_DB: expenselit
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=pt_BR.UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5435:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d expenselit"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - expenselit-network


volumes:
  postgres_data:
    driver: local

networks:
  expenselit-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

