# Generated by Django 5.2.5 on 2025-09-04 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Descrição"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                ("horary", models.TimeField(verbose_name="Horário")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food and drink", "Comida e bebida"),
                            ("bills and services", "Contas e serviços"),
                            ("electronics", "Eletrônicos"),
                            ("family and friends", "Amizades e Família"),
                            ("pets", "Animais de estimação"),
                            ("digital signs", "Assinaturas digitais"),
                            ("house", "Casa"),
                            ("purchases", "Compras"),
                            ("donate", "Doações"),
                            ("education", "Educação"),
                            ("loans", "Empréstimos"),
                            ("entertainment", "Entretenimento"),
                            ("taxes", "Impostos"),
                            ("investments", "Investimentos"),
                            ("others", "Outros"),
                            ("vestuary", "Roupas"),
                            ("health and care", "Saúde e cuidados pessoais"),
                            ("professional services", "Serviços profissionais"),
                            ("supermarket", "Supermercado"),
                            ("rates", "Taxas"),
                            ("transport", "Transporte"),
                            ("travels", "Viagens"),
                        ],
                        max_length=200,
                        verbose_name="Categoria",
                    ),
                ),
                ("payed", models.BooleanField(verbose_name="Pago")),
                (
                    "merchant",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Estabelecimento",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Local da Compra",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Dinheiro"),
                            ("debit_card", "Cartão de Débito"),
                            ("credit_card", "Cartão de Crédito"),
                            ("pix", "PIX"),
                            ("transfer", "Transferência"),
                            ("check", "Cheque"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Método de Pagamento",
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="expenses/receipts/",
                        verbose_name="Comprovante",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "recurring",
                    models.BooleanField(
                        default=False, verbose_name="Despesa Recorrente"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Diário"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensal"),
                            ("quarterly", "Trimestral"),
                            ("semiannual", "Semestral"),
                            ("annual", "Anual"),
                        ],
                        help_text="Apenas se for recorrente",
                        max_length=20,
                        null=True,
                        verbose_name="Frequência",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        max_length=200,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.account",
                        verbose_name="Conta",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.member",
                        verbose_name="Membro Responsável",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="expenses_ex_date_2850f8_idx"),
                    models.Index(
                        fields=["category", "date"],
                        name="expenses_ex_categor_125683_idx",
                    ),
                    models.Index(
                        fields=["account", "date"],
                        name="expenses_ex_account_aad602_idx",
                    ),
                    models.Index(
                        fields=["payed", "date"], name="expenses_ex_payed_daa7ed_idx"
                    ),
                    models.Index(
                        fields=["account", "category"],
                        name="expenses_ex_account_7ed937_idx",
                    ),
                ],
            },
        ),
    ]
