# Generated by Django 5.2.5 on 2025-09-04 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        default="Conta", max_length=200, verbose_name="Nome da conta"
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        choices=[
                            ("NUB", "Nubank"),
                            ("SIC", "Sicoob"),
                            ("MPG", "Mercado Pago"),
                            ("IFB", "Ifood Benefícios"),
                            ("CEF", "Caixa Econômica Federal"),
                        ],
                        default="CEF",
                        max_length=200,
                        unique=True,
                        verbose_name="Insitution",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CC", "Conta Corrente"),
                            ("CS", "Conta Salário"),
                            ("FG", "Fundo de Garantia"),
                            ("VA", "Vale Alimentação"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de Conta",
                    ),
                ),
                (
                    "account_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="accounts/",
                        verbose_name="Logo da conta",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "_account_number",
                    models.TextField(
                        blank=True,
                        help_text="Campo criptografado",
                        null=True,
                        verbose_name="Número da Conta (Criptografado)",
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Agência"
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Código do Banco",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Saldo Atual",
                    ),
                ),
                (
                    "minimum_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Saldo Mínimo",
                    ),
                ),
                (
                    "opening_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Abertura"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição/Observações"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.member",
                        verbose_name="Proprietário",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta",
                "verbose_name_plural": "Contas",
                "ordering": ["-account_name"],
            },
        ),
    ]
