# Generated by Django 5.2.5 on 2025-09-04 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Revenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Excluído"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                ("horary", models.TimeField(verbose_name="Horário")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("deposit", "Depósito"),
                            ("award", "Prêmio"),
                            ("salary", "Salário"),
                            ("ticket", "Vale"),
                            ("income", "Rendimentos"),
                            ("refund", "Reembolso"),
                            ("cashback", "Cashback"),
                            ("transfer", "Transferência Recebida"),
                            ("received_loan", "Empréstimo Recebido"),
                            ("loan_devolution", "Devolução de empréstimo"),
                        ],
                        max_length=200,
                        verbose_name="Categoria",
                    ),
                ),
                ("received", models.BooleanField(verbose_name="Recebido")),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Fonte da Receita",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Valor de Impostos",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Líquido",
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="revenues/receipts/",
                        verbose_name="Comprovante",
                    ),
                ),
                (
                    "recurring",
                    models.BooleanField(
                        default=False, verbose_name="Receita Recorrente"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Diário"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensal"),
                            ("quarterly", "Trimestral"),
                            ("semiannual", "Semestral"),
                            ("annual", "Anual"),
                        ],
                        help_text="Apenas se for recorrente",
                        max_length=20,
                        null=True,
                        verbose_name="Frequência",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.account",
                        verbose_name="Conta",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.member",
                        verbose_name="Membro Responsável",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="revenues_re_date_a4d9df_idx"),
                    models.Index(
                        fields=["category", "date"],
                        name="revenues_re_categor_d0d527_idx",
                    ),
                    models.Index(
                        fields=["account", "date"],
                        name="revenues_re_account_60351f_idx",
                    ),
                    models.Index(
                        fields=["received", "date"],
                        name="revenues_re_receive_f7dd12_idx",
                    ),
                    models.Index(
                        fields=["account", "category"],
                        name="revenues_re_account_78a025_idx",
                    ),
                ],
            },
        ),
    ]
